version: "3.9"
services:
  n1cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n1cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n1cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n1cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n2cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n2cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n2cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n2cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n3cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n3cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n3cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n3cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n4cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n4cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n4cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n4cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n5cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n5cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n5cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n5cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n6cm:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-cm
    container_name: n6cm
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n6cm.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n6cm.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

networks:
  main: