version: "3.9"
services:
  ops:
    build:
      context: .
      dockerfile: ./build/Dockerfile-x86_64-rhel8-om
    container_name: ops
    deploy:
      resources:
        limits:
          cpus: '2.000'
          memory: 8G
        reservations:
          cpus: '1.000'
          memory: 4G
    hostname: ops.om.internal
    image: rhel8-om:0.0
    networks:
      main:
        aliases:
          - ops.alt.internal
    privileged: true
    ports:
      - "8080:8080"
      - "8443:8443"
      - "25999:25999"

  node1-om:
    build:
      context: .
      dockerfile: ./build/Dockerfile-x86_64-rhel8-node
    container_name: node1-om
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 2G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: node1.om.internal
    image: rhel8-node:0.0
    networks:
      main:
        aliases:
          - node1.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  metadata:
    build:
      context: .
      dockerfile: ./build/Dockerfile-x86_64-rhel8-node
    container_name: metadata
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.75G
        reservations:
          cpus: '0.500'
          memory: 0.75G
    hostname: metadata.om.internal
    image: rhel8-node:0.0
    networks:
      main:
        aliases:
          - metadata.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  oplog:
    build:
      context: .
      dockerfile: ./build/Dockerfile-x86_64-rhel8-node
    container_name: oplog
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.75G
        reservations:
          cpus: '0.500'
          memory: 0.75G
    hostname: oplog.om.internal
    image: rhel8-node:0.0
    networks:
      main:
        aliases:
          - oplog.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  blockstore:
    build:
      context: .
      dockerfile: ./build/Dockerfile-x86_64-rhel8-node
    container_name: blockstore
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.75G
        reservations:
          cpus: '0.500'
          memory: 0.75G
    hostname: blockstore.om.internal
    image: rhel8-node:0.0
    networks:
      main:
        aliases:
          - blockstore.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  proxy:
    image: diouxx/squid
    networks:
      main:
        aliases:
          - proxy.alt.internal
    container_name: proxy
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 0.5G
        reservations:
          cpus: '0.250'
          memory: 0.5G
    hostname: proxy.om.internal
    ports:
      - "3128:3128"
    restart: always

  lb:
    build:
      context: .
      dockerfile: ./build/Dockerfile-nginx-lb
    networks:
      main: 
        aliases:
         - lb.alt.internal
    container_name: lb.om.internal
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 0.5G
        reservations:
          cpus: '0.250'
          memory: 0.5G
    ports: 
      - "80:80"
    restart: always

networks:
  main:
