version: "3.9"
services:
  n1:
    build:
      context: .
      dockerfile: Dockerfile-x86-rhel8
    container_name: n1
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n1.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n1.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n2:
    build:
      context: .
      dockerfile: Dockerfile-x86-rhel8
    container_name: n2
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n2.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n2.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  n3:
    build:
      context: .
      dockerfile: Dockerfile-x86-rhel8
    container_name: n3
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 3G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: n3.cm.internal
    image: mongo-infra:0.1
    networks:
      main:
        aliases:
          - n3.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

networks:
  main: